### ISSUE TITLE
Importer du contenu par FTP

### ISSUE THREAD

**Issue by yec7uF3ucu2uteku** [EsupPortail/pod#107]
Bonjour,

Est-ce que la fonction d'import en FTP, pour permettre par exemple le dépot de fichier depuis des enregistreurs situés en amphis existe ?
Comment est-il possible de faire le lien avec l'utilisateur propriétaire de la vidéo ?
Si non, quelle est la complexité d'un tel développement ?

Merci pour vos réponses,
Mathieu

**Comment by ptitloup** [comment]
Bonjour,
Oui nous avons mis ce système en place ici à Lille1 mais ce procéder 
n'est pas documenté. Vous pouvez regarder toute la partie "mediacourse"
N'hésitez pas à me contacter pour plus de renseignement
Bien cordialement


Le 22/05/2016 17:26, yec7uF3ucu2uteku a écrit :
>
> Bonjour,
>
> Est-ce que la fonction d'import en FTP, pour permettre par exemple le 
> dépot de fichier depuis des enregistreurs situés en amphis existe ?
> Si non, quelle est la complexité d'un tel développement ?
>
> Merci pour vos réponses,
> Mathieu
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/EsupPortail/pod/issues/107>
>


-- 
Signature Nicolas CAN

*Nicolas CAN*
Ingénieur développement et intégration d'application
Responsable informatique documentaire
Service WEB-ENT - Centre de Ressources Informatiques
Tel : (+33) 03 20 33 60 73
Courriel : nicolas.can@univ-lille1.fr <mailto:nicolas.can@univ-lille1.fr>

université lille1 sciences et technologie <http://www.univ-lille1.fr> 	

*Université de Lille, Sciences et Technologies*
Service Commun de Documentation - Bat. A5
Boulevard Paul Langevin
59655 Villeneuve d'Ascq Cedex

http://www.univ-lille1.fr

**Comment by yec7uF3ucu2uteku** [comment]
Bonjour,

Merci pour cette réponse qui m'indique la direction.
Comment faites-vous le lien entre le fichier uploadé et l'utilisateur propriétaire ?

Cordialement,
Mathieu

**Comment by ptitloup** [comment]
Bonjour
Pouvez vous me contacter directement par mail afin que l'on puisse écahnger directement ?
Merci

**Comment by yec7uF3ucu2uteku** [comment]
Bonjour,

Ca sera avec grand plaisir, mais je ne trouve pas votre addresse sur votre profil. Pouvez-vous svp me contacter sur mathieu (at) avinit.fr ?

Merci,
Mathieu

**Comment by ptitloup** [comment]
Suite à notre conversation téléphonique, je clos cette issue.
