### ISSUE TITLE
 Problème avec ElasticSearch 5.1.1

### ISSUE THREAD

**Issue by Maimee** [EsupPortail/pod#186]
Bonjour à tous,

J'ai effectué une installation de la dernière version de Pod chez moi en suivant la procédure du wiki.
Malheureusement, je n'arrive pas à créer l'index pod via la commande : python manage.py create_pod_index, qui me retourne cette erreur 

> Pod index already exists: mapper_parsing_exception

Est-il possible que ce soit dû à une incompatibilité avec Elasticsearch 5.1.X comme ç'avait été le [cas pour la 2.X](https://github.com/EsupPortail/pod/issues/78) ?

En vous remerciant pour votre aide par avance,
A bientôt,

Laura

**Comment by DrClockwork** [comment]
Bonjour,

En effet il y a incompatibilité avec la version 5 d'Elasticsearch. C'est pour cela que dans le wiki le lien fournit pour le guide d'installation d'Elasticsearch est celui de la version 2.4.x. Je vais modifier le wiki pour ajouter cette précision concernant les versions, c'est un oubli de ma part.

Cordialement,

Joël

**Comment by Maimee** [comment]
Je te remercie Joël pour cette précision.
Ça m'apprendra aussi, une mauvaise habitude pour soit disant m'éviter une mise à jour...
Je refais l'installation de ES 2.4 et et vous fais un retour pour clôture l'issue.
Cordialement,
Laura

**Comment by Maimee** [comment]
Effectivement ça fonctionne mieux en installant la version 2.4.
Merci encore,
Laura
