### ISSUE TITLE
Page d'accueil en erreur à l'installation

### ISSUE THREAD

**Issue by SaintGenesLaSalle** [EsupPortail/pod#189]
Bonjour,

Je viens de faire une réinstallation sur une machine vierge et la page d'accueil ne s'affiche pas.

J'obtiens ceci :

> Page not found (404)
Request Method:
GET
Request URL:
http://pod:8080/
Using the URLconf defined in pod_project.urls, Django tried these URL patterns, in this order: 
^favicon\.ico$ 
...
^media\/(?P<path>.*)$ 
The current URL, , didn't match any of these.

En saisissant leur urls, d'autres pages s'affichent (http://pod:8080/videos/ par exemple) et la navigation est opérationnelle hors accueil.

Merci de vos conseils

Alain

**Comment by ptitloup** [comment]
Bonjour,
Lors de l'installation, il faut lancer la commande pour charger les données en base de données (ce qui créé une page d'accueil par défaut). Voici ce qu'il y a dans le wiki : 

On charge ensuite des données de base en base de données :
(django_pod)pod@podvm:~/django_projects/pod/pod_project$ python manage.py loaddata core/fixtures/initial_data.json

Et on créé le superutilisateur :

(django_pod)pod@podvm:~/django_projects/pod/pod_project$ python manage.py createsuperuser --username root

Cordialement
Nicolas CAN
