### ISSUE TITLE
Problème avec ElasticSearch 2.0

### ISSUE THREAD

**Issue by dotmobo** [EsupPortail/pod#78]
Bonjour,

J'essaye d'installer la dernière version de pod en local sur ma machine, et je rencontre un problème avec ElasticSearch 2.0 et la commande create_pod_index.

En effet, la commande `python manage.py create_pod_index` me renvoie l'erreur suivante:

`l'index Pod est existant : {u'caused_by': {u'reason': u'analyzer on field [chapters] must be set when search_analyzer is set', u'type': u'mapper_parsing_exception'}, u'root_cause': [{u'reason': u'analyzer on field [chapters] must be set when search_analyzer is set', u'type': u'mapper_parsing_exception'}], u'type': u'mapper_parsing_exception', u'reason': u'mapping [pod]'}`

Ma configuration d'ElasticSearch 2.0 est la suivante:
```
#POD
cluster.name: pod
node.name: "Pod1"
network.host: 127.0.0.1
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["127.0.0.1"]
```

Merci pour votre aide,

Cordialement,

Morgan - Unistra

**Comment by dotmobo** [comment]
Le code fonctionne sous ElasticSearch 1.6. Il doit donc y avoir une incompatibilité avec le version 2.0.

**Comment by ptitloup** [comment]
Je viens de merger une PR pour rendre le template compatible avec ES 2.X, tu peux tester si tout est ok pour toi ?
Merci
