### ISSUE TITLE
Lien avec Moodle

### ISSUE THREAD

**Issue by ishirox** [EsupPortail/pod#91]
Bonjour,
Est ce qu'il existe un lien quelconque au niveau de la programmation entre Lillepod1 et la plate-forme moodle ?

Merci

**Comment by ptitloup** [comment]
Bonjour,
Nous prévoyons de développer un module Moodle pour integrer directement une video de Pod dans Moodle. Nous avons travaille sur le moteur de recherche pour faciliter cela.
Cordialement

**Comment by yec7uF3ucu2uteku** [comment]
Bonjour,

Est-ce que ce module est maintenant disponible ?

Cordialement,
Mathieu
